const french = [
  { source: "à", target: "to" },
  { source: "à bientôt", target: "see you soon" },
  { source: "à cause de", target: "because of" },
  { source: "à côté de", target: "next to" },
  { source: "à demain", target: "see you tomorrow" },
  { source: "à droite", target: "on/to the right" },
  { source: "à gauche", target: "on/to theft" },
  { source: "àavenir", target: "in the future" },
  { source: "àétranger", target: "abroad" },
  { source: "àheure", target: "on time" },
  { source: "à fois", target: "at the same time" },
  { source: "à mon avis", target: "in my opinion" },
  { source: "à part", target: "apart from" },
  { source: "à peine", target: "scarcely" },
  { source: "à quelle heure ?", target: "at what time?" },
  { source: "à temps partiel", target: "part-time" },
  { source: "à tout àheure", target: "see you soon/later" },
  { source: "à travers", target: "across" },
  { source: "absolument", target: "absolutely" },
  { source: "accro", target: "addicted" },
  { source: "accueil", target: "welcome" },
  { source: "acheter", target: "to buy" },
  { source: "actualitéss", target: "news" },
  { source: "ado", target: "adolescent" },
  { source: "aéroport", target: "airport" },
  { source: "affreux", target: "awful" },
  { source: "Afrique/africain", target: "Africa/African" },
  { source: "agence de voyages", target: "travel agency" },
  { source: "agent de police", target: "policeman" },
  { source: "agir", target: "to act" },
  { source: "agneau", target: "lamb" },
  { source: "agréable", target: "pleasant" },
  { source: "agresser", target: "to attack" },
  { source: "aider", target: "to help" },
  { source: "ail", target: "garlic" },
  { source: "aimable", target: "kind" },
  { source: "aîné", target: "elder" },
  { source: "ainsi", target: "so" },
  { source: "aire de jeux", target: "play area" },
  { source: "alcool", target: "alcohol" },
  { source: "alcoolique", target: "alcoholic" },
  { source: "Algérie/algérien", target: "Algeria/Algerian" },
  { source: "alimentation", target: "food" },
  { source: "Allemagne/allemand", target: "Germany/German" },
  { source: "aller bien", target: "to be well" },
  { source: "aller mieux", target: "to be better" },
  { source: "allô", target: "hello" },
  { source: "allumer", target: "to switch on" },
  { source: "alors", target: "so, therefore" },
  { source: "Alpess", target: "Alps" },
  { source: "améliorer", target: "to improve" },
  { source: "amer/amère", target: "sour" },
  { source: "amitiés", target: "best wishes" },
  { source: "amour", target: "love" },
  { source: "amusant", target: "funny" },
  { source: "an", target: "year" },
  { source: "ananas", target: "pineapple" },
  { source: "Angleterre/anglais", target: "England/English" },
  { source: "animé", target: "lively" },
  { source: "année", target: "year" },
  { source: "année sabbatique", target: "gap year" },
  { source: "apprendre", target: "toarn" },
  { source: "apprenti(e)", target: "apprentice" },
  { source: "après", target: "after" },
  { source: "après-demain", target: "the day after tomorrow" },
  { source: "après-midi", target: "afternoon" },
  { source: "arbre", target: "tree" },
  { source: "argent", target: "silver" },
  { source: "argent", target: "money" },
  { source: "armoire", target: "wardrobe" },
  { source: "arrivée", target: "arrival" },
  { source: "ascenseur", target: "lift" },
  { source: "assez", target: "enough" },
  { source: "assiette", target: "plate/dish" },
  { source: "assis", target: "sitting" },
  { source: "association caritative", target: "charity" },
  { source: "attaque", target: "attack" },
  { source: "attendre", target: "to wait" },
  { source: "atterrir", target: "tond" },
  { source: "au bord de", target: "at the side/edge of" },
  {
    source: "au bout de",
    target: "at the end of (iength, rather than time)",
  },
  { source: "au fond de", target: "at the back of, at the bottom of" },
  { source: "au lieu de", target: "instead of" },
  { source: "au milieu de", target: "in the middle of" },
  { source: "au secours", target: "help" },
  { source: "au-dessous de", target: "beneath" },
  { source: "au-dessus de", target: "above" },
  { source: "auberge de jeunesse", target: "youth hostel" },
  { source: "augmenter", target: "to increase" },
  { source: "aujourd’hui", target: "today" },
  { source: "auparavant", target: "formerly, in the past" },
  { source: "aussi", target: "also" },
  { source: "auto", target: "car" },
  { source: "autobus", target: "bus" },
  { source: "automne", target: "autumn" },
  { source: "autoroute", target: "motorway" },
  { source: "autour de", target: "around" },
  { source: "avant", target: "before" },
  { source: "avant-hier", target: "the day before yesterday" },
  { source: "avantage", target: "advantage" },
  { source: "avenir", target: "future" },
  { source: "aventure", target: "adventure" },
  { source: "averse", target: "shower" },
  { source: "avertir", target: "to warn" },
  { source: "avion", target: "plane" },
  { source: "avis", target: "opinion" },
  { source: "avocat", target: "lawyer" },
  { source: "avoir envie de", target: "to want to" },
  { source: "avoirintention de", target: "to intend" },
  { source: "avoir raison", target: "to be right" },
  { source: "avoir sommeil", target: "to be sleepy" },
  { source: "avoir tort", target: "to be wrong" },
  { source: "avoir  ans", target: "to be...years old" },
  { source: "bac(calauréat)", target: "A-level(s)" },
  { source: "bagagess", target: "luggage" },
  { source: "bague", target: "ring" },
  { source: "bain", target: "bath" },
  { source: "bande", target: "gang" },
  { source: "banlieue", target: "suburb" },
  { source: "barbant", target: "boring" },
  { source: "barbe", target: "beard" },
  { source: "bas", target: "low" },
  { source: "basket", target: "basketball" },
  { source: "basketss", target: "trainers" },
  { source: "bateau", target: "boat" },
  { source: "bâtiment", target: "building" },
  { source: "bavard", target: "chatty/talkative" },
  { source: "beau-père", target: "step-father" },
  { source: "beau/belle/bel", target: "beautiful" },
  { source: "beaucoup/plus/le plus", target: "lots/more/the most" },
  { source: "Belgique/belge", target: "Belgium/Belgian" },
  { source: "belle-mère", target: "step-mother" },
  { source: "besoin", target: "need" },
  { source: "bête", target: "stupid" },
  { source: "béton", target: "concrete" },
  { source: "beurre", target: "butter" },
  { source: "bibliothèque", target: "library" },
  { source: "bien cuit", target: "well cooked" },
  { source: "bien entendu", target: "of course" },
  { source: "bien équipé", target: "well equipped" },
  { source: "bien sûr", target: "of course" },
  { source: "bien sûr", target: "of course" },
  { source: "bien/mieux/le mieux", target: "well/better/best" },
  { source: "bientôt", target: "soon" },
  { source: "bienvenue", target: "welcome" },
  { source: "bière", target: "beer" },
  { source: "bijou", target: "jewel" },
  { source: "bijouterie", target: "jeweller’s shop" },
  { source: "billet", target: "ticket" },
  { source: "bloggeur", target: "blogger" },
  { source: "blouson", target: "coat/jacket" },
  { source: "bœuf", target: "beef" },
  { source: "boire", target: "to drink" },
  { source: "bois", target: "wood" },
  { source: "boisson", target: "drink" },
  { source: "boîte", target: "box, tin" },
  { source: "boîte", target: "(cardboard) box" },
  { source: "bon anniversaire", target: "happy birthday" },
  { source: "bon appétit", target: "enjoy your meal" },
  { source: "bon marché", target: "cheap" },
  { source: "bon voyage", target: "have a good trip" },
  { source: "bon/meilleur/le meilleur", target: "good/better/best" },
  { source: "bonbon", target: "sweet" },
  { source: "bonheur", target: "happiness" },
  { source: "bonne année", target: "happy new year" },
  { source: "bonne chance", target: "good luck" },
  { source: "bonne idée", target: "good idea" },
  { source: "bonne nuit", target: "good night" },
  { source: "bonnes vacances", target: "have a good holiday" },
  { source: "bonsoir", target: "good evening" },
  { source: "bord de mer", target: "seaside" },
  { source: "boucher", target: "butcher" },
  { source: "boucherie", target: "butcher’s shop" },
  { source: "bouclé", target: "curly" },
  { source: "boulanger", target: "baker" },
  { source: "boulangerie", target: "bakery" },
  { source: "boulot", target: "job" },
  { source: "bouteille", target: "bottle" },
  { source: "bouton", target: "spot" },
  { source: "bricolage", target: "DIY" },
  { source: "briller", target: "to shine" },
  { source: "bronzer", target: "to sunbathe" },
  { source: "brouillard", target: "fog" },
  { source: "bruit", target: "noise" },
  { source: "brume", target: "mist" },
  { source: "bruyant", target: "noisy" },
  { source: "bulletin scolaire", target: "school report" },
  { source: "bureau", target: "office" },
  { source: "c’est combien ?", target: "how much is it?" },
  { source: "c’est quel jour ?", target: "what day is it?" },
  { source: "c’est quelle date ?", target: "what is the date?" },
  { source: "c’est-à-dire", target: "that is to say, i.e." },
  { source: "ça dépend", target: "that depends" },
  { source: "ça m’énerve", target: "it gets on my nerves" },
  { source: "ça m’est égal", target: "it’s all the same to me" },
  { source: "ça me fait rire", target: "it makes meugh" },
  { source: "ça me plaît", target: "I like it" },
  {
    source: "ça ne me dit rien",
    target: "it means nothing to me/I don't fancy that/I don't feel like it",
  },
  { source: "ça s’écrit comment ?", target: "how is that written?" },
  { source: "ça suffit", target: "that’s enough" },
  { source: "cacher", target: "to hide" },
  { source: "cadeau", target: "present" },
  { source: "caisse", target: "till" },
  { source: "calculette", target: "calculator" },
  { source: "calme", target: "quiet" },
  { source: "caméscope", target: "camcorder" },
  { source: "campagne", target: "countryside" },
  { source: "campagne", target: "countryside" },
  { source: "campagne", target: "campaign" },
  { source: "canard", target: "duck" },
  { source: "cancer", target: "(lung) cancer" },
  { source: "candidat", target: "candidate" },
  { source: "car de ramassage", target: "school bus" },
  { source: "car", target: "because" },
  { source: "car", target: "coach" },
  { source: "carré", target: "square" },
  { source: "carte bancaire", target: "bank card" },
  { source: "carte", target: "map" },
  { source: "carte postale", target: "postcard" },
  { source: "casse-croûte", target: "snack" },
  { source: "casse-pieds", target: "annoying" },
  { source: "casser", target: "to break" },
  { source: "cave", target: "cellar" },
  {
    source: "CDI centre de documentation et d’information",
    target: "resource centre",
  },
  { source: "ceinture", target: "belt" },
  { source: "célèbre", target: "famous" },
  { source: "célibataire", target: "single" },
  { source: "centre commercial", target: "shopping centre" },
  { source: "centre de recyclage", target: "recycling centre" },
  { source: "centre sportif", target: "sports centre" },
  { source: "centre-ville", target: "town centre" },
  { source: "cependant", target: "however" },
  { source: "cerise", target: "cherry" },
  { source: "certainement", target: "certainly" },
  {
    source: "CES collège d’enseignement secondaire",
    target: "secondary school",
  },
  { source: "chaleur", target: "heat" },
  { source: "chambre d’hôte", target: "bed and breakfast" },
  { source: "chambre de famille", target: "family room" },
  { source: "champ", target: "field" },
  { source: "champignon", target: "mushroom" },
  { source: "chanson", target: "song" },
  { source: "chanter", target: "to sing" },
  { source: "chanteur/chanteuse", target: "singer" },
  { source: "chapeau", target: "hat" },
  { source: "charbon", target: "coal" },
  { source: "charcuterie", target: "delicatessen" },
  { source: "châtain", target: "light brown" },
  { source: "chauffage central", target: "central heating" },
  { source: "chaussette", target: "sock" },
  { source: "chaussure", target: "shoe" },
  { source: "chemin de fer", target: "railway" },
  { source: "chemin", target: "way" },
  { source: "chemise", target: "shirt" },
  { source: "cher", target: "dear" },
  { source: "chercher", target: "to look for" },
  { source: "chercher", target: "to look for" },
  { source: "cheval", target: "horse" },
  { source: "cheveuxs", target: "hair" },
  { source: "chez", target: "at the house of" },
  { source: "chimie", target: "chemistry" },
  { source: "Chine/chinois", target: "China/Chinese" },
  { source: "chocolat", target: "chocolate" },
  { source: "choisir", target: "to choose" },
  { source: "choix", target: "choice" },
  { source: "chômage", target: "unemployment" },
  { source: "chorale", target: "choir" },
  { source: "chose", target: "thing" },
  { source: "chou", target: "cabbage" },
  { source: "chou-fleur", target: "cauliflower" },
  { source: "chouette", target: "great" },
  { source: "ciel", target: "sky" },
  { source: "cinquième", target: "fifth" },
  { source: "circulation", target: "traffic" },
  { source: "citron", target: "lemon" },
  { source: "clair", target: "light" },
  { source: "clavier", target: "keyboard" },
  { source: "clé", target: "key" },
  { source: "climat", target: "climate" },
  { source: "climatisation", target: "air conditioning" },
  { source: "cliquer", target: "to click" },
  { source: "club des jeunes", target: "youth club" },
  { source: "coiffeur", target: "hairdresser" },
  { source: "collège", target: "secondary school" },
  { source: "colline", target: "hill" },
  { source: "colonie de vacances", target: "holiday/summer camp" },
  { source: "combattre", target: "to combat" },
  { source: "combien ?", target: "how much, how many?" },
  { source: "commander", target: "to order" },
  { source: "comme", target: "as" },
  { source: "comme ci comme ça", target: "so-so" },
  { source: "commencer", target: "to start" },
  { source: "comment ?", target: "how?" },
  { source: "commercess", target: "shops" },
  { source: "commissariat", target: "police station" },
  { source: "Common questions", target: "" },
  { source: "complet/complète", target: "full" },
  { source: "compliqué", target: "complicated" },
  { source: "compréhensif/compréhensive", target: "understanding" },
  { source: "comprendre", target: "to understand" },
  { source: "comptable", target: "accountant" },
  { source: "compte", target: "account" },
  { source: "compter (sur)", target: "to count" },
  { source: "concours", target: "competition" },
  { source: "conduire", target: "to drive" },
  { source: "confiance", target: "trust" },
  { source: "confiture", target: "jam" },
  { source: "connaître", target: "to know" },
  { source: "conseil", target: "advice" },
  { source: "conseiller d’orientation", target: "careers adviser" },
  { source: "console de jeux", target: "games console" },
  { source: "consommation", target: "consumption" },
  { source: "content", target: "happy" },
  { source: "contre", target: "against" },
  { source: "copain/copine", target: "friend" },
  { source: "corriger", target: "to correct" },
  { source: "couche d’ozone", target: "ozoneyer" },
  { source: "couloir", target: "corridor" },
  { source: "coupable", target: "guilty" },
  { source: "courir", target: "to run" },
  { source: "courrier électronique", target: "email" },
  { source: "cours", target: "lesson" },
  { source: "course", target: "race" },
  { source: "court", target: "short" },
  { source: "court", target: "short" },
  { source: "coûter", target: "to cost" },
  { source: "couture", target: "sewing" },
  { source: "couvert", target: "overcast" },
  { source: "cravate", target: "tie" },
  { source: "crème solaire", target: "sun cream" },
  { source: "crêpe", target: "pancake" },
  { source: "crise cardiaque", target: "heart attack" },
  { source: "croire", target: "to believe" },
  { source: "croire", target: "to believe" },
  { source: "croisière", target: "cruise" },
  { source: "cruditéss", target: "raw chopped vegetables" },
  { source: "cuir", target: "leather" },
  { source: "cuisine", target: "kitchen/cooking" },
  { source: "cultiver", target: "to grow" },
  {
    source:
      "Customs and festivals in French-speaking countries and communities ",
    target: "",
  },
  {
    source: "Customs and festivals in French-speaking countries/communities",
    target: "",
  },
  { source: "d’abord", target: "at first" },
  { source: "d’accord", target: "ok" },
  { source: "d’habitude", target: "usually" },
  { source: "d’où ?", target: "from where?" },
  {
    source: "d’un côté / deautre côté",
    target: "on the one hand/on the other hand",
  },
  { source: "dangereux", target: "dangerous" },
  { source: "de", target: "of" },
  { source: "de bonne heure", target: "early" },
  { source: "de chaque côté", target: "from each side" },
  { source: "deautre côté", target: "from the other side" },
  { source: "de mauvaise humeur", target: "bad tempered" },
  { source: "de nouveau", target: "again" },
  { source: "de quelle couleur ?", target: "what colour?" },
  { source: "de rien", target: "don't mention it" },
  { source: "de taille moyenne", target: "medium height" },
  { source: "de temps en temps", target: "from time to time" },
  { source: "déboisement", target: "deforestation" },
  { source: "débouché", target: "prospect/job prospect/opportunity" },
  { source: "debout", target: "standing" },
  { source: "début", target: "start" },
  { source: "débuter", target: "to begin" },
  { source: "déchetss", target: "rubbish" },
  { source: "décoller", target: "to take off" },
  { source: "défilé", target: "procession" },
  { source: "dégoûtant", target: "disgusting" },
  { source: "déjà", target: "already" },
  { source: "déjeuner", target: "lunch" },
  { source: "demain", target: "tomorrow" },
  { source: "demander", target: "to ask" },
  { source: "déménager", target: "to move house" },
  { source: "demi", target: "half" },
  { source: "demi-frère", target: "half-brother" },
  { source: "demi-sœur", target: "half-sister" },
  { source: "démodé", target: "old-fashioned" },
  { source: "départ", target: "departure" },
  { source: "dépenser", target: "to spend" },
  { source: "déprimé", target: "depressed" },
  { source: "depuis", target: "since" },
  { source: "déranger", target: "to disturb" },
  { source: "dernier/dernière", target: "last" },
  { source: "derrière", target: "behind" },
  { source: "désagréable", target: "unpleasant" },
  { source: "désavantage", target: "disadvantage" },
  { source: "descendre", target: "to stay" },
  { source: "désintoxiquer", target: "to detox" },
  { source: "désirer", target: "to want" },
  { source: "désolé", target: "sorry" },
  { source: "dessin animé", target: "cartoon" },
  { source: "dessin", target: "art" },
  { source: "dessinateur de mode", target: "fashion designer" },
  { source: "détester", target: "to hate" },
  { source: "détruire", target: "to destroy" },
  { source: "dette", target: "debt" },
  { source: "deuxième", target: "second" },
  { source: "devant", target: "in front of" },
  { source: "devenir", target: "to become" },
  { source: "devoir", target: "to have to" },
  { source: "devoirss", target: "homework" },
  { source: "difficulté", target: "difficulty" },
  { source: "dinde", target: "turkey" },
  { source: "dîner", target: "evening meal" },
  { source: "diplôme", target: "qualification" },
  { source: "dire", target: "to say" },
  { source: "dire", target: "to say" },
  { source: "directeur", target: "headmaster" },
  { source: "directrice", target: "headmistress" },
  { source: "discuter", target: "to discuss" },
  { source: "disparaître", target: "to disappear" },
  { source: "disponible", target: "available" },
  { source: "distractionss", target: "things to do" },
  { source: "distribuer", target: "to give out" },
  { source: "dixième", target: "tenth" },
  { source: "dizaine une", target: "about 10" },
  { source: "donc", target: "so" },
  { source: "donner sur", target: "to overlook" },
  { source: "dormir", target: "to sleep" },
  { source: "dortoir", target: "dormitory" },
  { source: "douche", target: "shower" },
  { source: "doué", target: "gifted" },
  { source: "douleur", target: "pain" },
  { source: "Douvres", target: "Dover" },
  { source: "doux", target: "mild" },
  { source: "douzaine une", target: "dozen" },
  { source: "dresser", target: "to put up" },
  { source: "drogue", target: "drug" },
  { source: "droit", target: "right" },
  { source: "drôle", target: "funny" },
  { source: "durer", target: "tost" },
  { source: "eau", target: "(mineral) water" },
  { source: "eau potable", target: "drinking water" },
  { source: "échange", target: "exchange" },
  { source: "écharpe", target: "scarf" },
  { source: "échecss", target: "chess" },
  { source: "échouer", target: "to fail" },
  { source: "éclair", target: "lightning" },
  { source: "éclaircie", target: "bright spell" },
  {
    source: "école",
    target: "(primary/secondary) school",
  },
  { source: "économiser", target: "to save" },
  { source: "Ecosse/écossais", target: "Scotland/Scottish" },
  { source: "écran", target: "screen" },
  { source: "écran tactile", target: "touch screen" },
  { source: "Education post-16", target: "" },
  { source: "Education post-16", target: "" },
  { source: "effacer", target: "to delete" },
  { source: "effet de serre", target: "greenhouse effect" },
  { source: "effets spéciauxs", target: "special effects" },
  { source: "effrayant", target: "frightening" },
  { source: "égal", target: "equal" },
  { source: "égalité", target: "equality" },
  { source: "église", target: "church" },
  { source: "égoïste", target: "selfish" },
  { source: "élargir", target: "to widen" },
  { source: "élève", target: "pupil" },
  { source: "emballage", target: "packaging" },
  { source: "embêtant", target: "annoying" },
  { source: "embouteillage", target: "traffic jam" },
  { source: "empêcher", target: "to prevent" },
  { source: "emplacement", target: "pitch (tent)" },
  { source: "emploi du temps", target: "timetable" },
  { source: "employé(e)", target: "employee" },
  { source: "employeur", target: "employer" },
  { source: "en", target: "in" },
  { source: "en attendant", target: "whilst waiting" },
  { source: "en avance", target: "in advance" },
  { source: "en bas", target: "down(stairs)" },
  { source: "en bonne forme", target: "fit" },
  { source: "en bonne santé", target: "in good health" },
  { source: "en ce moment", target: "at the moment" },
  { source: "en danger", target: "in danger" },
  { source: "en dehors de", target: "outside" },
  { source: "en face de", target: "opposite" },
  { source: "en général", target: "in general" },
  { source: "en haut", target: "up(stairs)" },
  { source: "en ligne", target: "online" },
  { source: "en même temps", target: "at the same time" },
  { source: "en plein air", target: "in the open air" },
  { source: "en première", target: "in year 12" },
  { source: "en retard", target: "late" },
  { source: "en seconde", target: "in year 11" },
  { source: "en terminale", target: "in year 13" },
  { source: "en train de", target: "(to be) doing" },
  { source: "enchanté", target: "delighted" },
  { source: "encore de", target: "more" },
  { source: "encore une fois", target: "once more" },
  { source: "endommager", target: "to damage" },
  { source: "endroit", target: "place" },
  { source: "énergie renouvelable", target: "renewable energy" },
  { source: "enfin", target: "atst" },
  { source: "ennui", target: "problem" },
  { source: "ennuyeux", target: "boring" },
  { source: "enquête", target: "enquiry" },
  { source: "enregistrer", target: "to record" },
  { source: "enrichissant", target: "enriching" },
  { source: "enseigner", target: "to teach" },
  { source: "ensemble", target: "together" },
  { source: "ensoleillé", target: "sunny" },
  { source: "ensuite", target: "next" },
  { source: "entouré", target: "surrounded" },
  { source: "entraînement", target: "training" },
  { source: "entre", target: "between" },
  { source: "entrée", target: "entry" },
  { source: "entreprise", target: "firm" },
  { source: "entretien", target: "interview" },
  { source: "environ", target: "about" },
  { source: "environnement", target: "environment" },
  { source: "envoyer", target: "to send" },
  { source: "épicé", target: "spicy" },
  { source: "épouser", target: "to marry" },
  { source: "épreuve", target: "test" },
  {
    source: "EPS éducation physique et sportive",
    target: "PE",
  },
  { source: "EPS", target: "PE" },
  { source: "épuiser", target: "to exhaust" },
  { source: "équilibré", target: "balanced" },
  { source: "équitation", target: "horse riding" },
  { source: "erreur", target: "error" },
  { source: "escalade", target: "rock climbing" },
  { source: "escalier", target: "staircase" },
  { source: "escargot", target: "snail" },
  { source: "espace vert", target: "green area" },
  { source: "Espagne/espagnol", target: "Spain/Spanish" },
  { source: "espèce", target: "type" },
  { source: "espérer", target: "to hope" },
  { source: "espérer", target: "to hope" },
  { source: "espoir", target: "hope" },
  { source: "esprit", target: "mind" },
  { source: "essayer", target: "to try" },
  { source: "essayer", target: "to try on" },
  { source: "essence", target: "petrol" },
  { source: "essoufflé", target: "breathless" },
  { source: "est", target: "east" },
  {
    source: "est-ce que ?",
    target: "expression put before a verb to make sentence into a question",
  },
  { source: "établissement", target: "establishment" },
  { source: "étage", target: "floor" },
  { source: "état", target: "state" },
  { source: "Etats-Uniss", target: "USA" },
  { source: "été", target: "summer" },
  { source: "éteindre", target: "to switch off" },
  { source: "étonnant", target: "amazing" },
  { source: "étonné", target: "astonished" },
  { source: "étrange", target: "strange" },
  { source: "étranger", target: "stranger/foreigner" },
  { source: "étroit", target: "narrow" },
  { source: "étudess", target: "study" },
  { source: "étudiant", target: "student" },
  { source: "étudier", target: "to study" },
  { source: "événement", target: "event" },
  { source: "évidemment", target: "obviously" },
  { source: "éviter", target: "to avoid" },
  { source: "examen", target: "examination" },
  { source: "excusez-moi", target: "excuse me" },
  { source: "expliquer", target: "to explain" },
  { source: "fâché", target: "angry" },
  { source: "facile", target: "easy" },
  { source: "facteur", target: "postman" },
  { source: "faculté", target: "university" },
  { source: "faible", target: "weak" },
  { source: "faible", target: "weak" },
  { source: "faire attention", target: "to pay attention" },
  { source: "faire beau", target: "to be fine" },
  { source: "faire des achats", target: "to shop" },
  { source: "faire du camping", target: "to go camping" },
  { source: "faire du recyclage", target: "to recycle" },
  { source: "faire connaissance", target: "to get to know" },
  { source: "faire grasse matinée", target: "to lie in, sleep in" },
  { source: "faire mauvais", target: "to be bad" },
  { source: "faire un régime", target: "to be on a diet" },
  { source: "fana de", target: "a fan of" },
  { source: "fatigué", target: "tired" },
  { source: "faute", target: "fault" },
  { source: "faux/fausse", target: "FALSE" },
  { source: "félicitations", target: "congratulations" },
  { source: "féliciter", target: "to congratulate" },
  { source: "femme", target: "wife/woman" },
  { source: "fenêtre", target: "window" },
  { source: "fer", target: "iron" },
  { source: "ferme", target: "farm" },
  { source: "fermer", target: "to close" },
  { source: "fermeture", target: "closure" },
  { source: "fermier", target: "farmer" },
  { source: "fête des mères", target: "Mother's Day" },
  { source: "fête des rois", target: "Twelfth Night/Epiphany" },
  { source: "fête du travail", target: "May Day" },
  { source: "fête", target: "festival, celebration" },
  { source: "fêter", target: "to celebrate" },
  { source: "feuilleton", target: "soap opera" },
  { source: "feux d’artifices", target: "fireworks" },
  { source: "fiançailless", target: "engagement" },
  { source: "fichier", target: "file" },
  { source: "fier/fière", target: "proud" },
  { source: "fille", target: "daughter/girl" },
  { source: "film de guerre", target: "war film" },
  { source: "film policier", target: "detective film" },
  { source: "fils", target: "son" },
  { source: "fin", target: "end" },
  { source: "fleur", target: "flower" },
  { source: "foie", target: "liver" },
  { source: "foire", target: "fair" },
  { source: "foncé", target: "dark" },
  { source: "forme", target: "fitness" },
  { source: "former", target: "to train" },
  { source: "formidable", target: "great" },
  { source: "fort", target: "strong" },
  { source: "forum", target: "chat room" },
  { source: "fou/folle", target: "mad" },
  { source: "foulard", target: "scarf" },
  { source: "four", target: "oven" },
  { source: "foyer", target: "home" },
  { source: "fraise", target: "strawberry" },
  { source: "framboise", target: "raspberry" },
  { source: "français", target: "French" },
  { source: "franchement", target: "frankly" },
  { source: "Free-time activities", target: "" },
  { source: "Free-time activities", target: "" },
  { source: "frisé", target: "curly" },
  { source: "frontière", target: "border" },
  { source: "fruits de mers", target: "seafood" },
  { source: "fumer", target: "to smoke" },
  { source: "gagner", target: "to earn" },
  { source: "gallois", target: "Wales/Welsh" },
  { source: "garder", target: "to look after" },
  { source: "garder", target: "to look after" },
  { source: "gare", target: "railway station" },
  { source: "gare routière", target: "bus station" },
  { source: "gaspiller", target: "to waste" },
  { source: "gâter", target: "to spoil" },
  { source: "gaz carbonique", target: "carbon dioxide" },
  { source: "gaz d’échappement", target: "exhaust fumes" },
  { source: "geler", target: "to freeze" },
  { source: "gêner", target: "to annoy" },
  { source: "généralement", target: "generally" },
  { source: "généreux/généreuse", target: "generous" },
  { source: "génial", target: "great" },
  { source: "genre", target: "type" },
  { source: "genss", target: "people" },
  { source: "gentil/gentille", target: "kind" },
  { source: "gilet", target: "waistcoat" },
  { source: "glace", target: "ice" },
  { source: "glace", target: "ice cream" },
  { source: "Global issues", target: "" },
  { source: "Global issues", target: "" },
  { source: "goûter", target: "to taste" },
  { source: "grand magasin", target: "department store" },
  { source: "grand-mère", target: "grandmother" },
  { source: "grand-père", target: "grandfather" },
  { source: "grande surface", target: "superstore" },
  {
    source: "Grande-Bretagne/britannique",
    target: "Great Britain/British",
  },
  { source: "grands-parentss", target: "grandparents" },
  { source: "gras", target: "fatty" },
  { source: "gratuit", target: "free" },
  { source: "grave", target: "serious" },
  { source: "gros", target: "fat" },
  { source: "gros/grosse", target: "fat" },
  { source: "guerre", target: "war" },
  { source: "habile", target: "clever" },
  { source: "habitant", target: "inhabitant" },
  { source: "habitude", target: "habit" },
  { source: "harcèlement", target: "bullying" },
  { source: "harceler", target: "to bully" },
  { source: "haricots vertss", target: "green beans" },
  { source: "haut", target: "high" },
  { source: "héberger", target: "to lodge" },
  { source: "herbe", target: "grass" },
  { source: "heureux/heureuse", target: "happy" },
  { source: "hier", target: "yesterday" },
  { source: "hiver", target: "winter" },
  {
    source: "HLM habitation à loyer modéré",
    target: "council/social housing accommodation",
  },
  { source: "Home, town, neighborhood and region", target: "" },
  { source: "Home,town, neighborhood and reigon", target: "" },
  { source: "horaire", target: "timetable" },
  { source: "hors d’haleine", target: "out of breath" },
  { source: "hors d’œuvre", target: "starter" },
  { source: "hôtel de ville", target: "town hall" },
  { source: "huitième", target: "eighth" },
  { source: "humide", target: "humid" },
  { source: "ici", target: "here" },
  { source: "idée", target: "idea" },
  { source: "il faut", target: "you must" },
  { source: "il y a", target: "ago" },
  { source: "île", target: "island" },
  { source: "immeuble", target: "block of flats" },
  { source: "immigré", target: "immigrant" },
  { source: "imprimante", target: "printer" },
  { source: "imprimer", target: "to print" },
  { source: "incendie", target: "fire" },
  { source: "incivilitéss", target: "rudeness" },
  { source: "inconnu", target: "unknown" },
  { source: "inconvénient", target: "disadvantage" },
  { source: "incroyable", target: "incredible" },
  { source: "infirmier", target: "nurse" },
  { source: "informaticien", target: "IT worker" },
  { source: "informatique", target: "IT" },
  { source: "ingénieur", target: "engineer" },
  { source: "injure", target: "insult" },
  { source: "injuste", target: "unfair" },
  { source: "inondation", target: "flood" },
  { source: "inonder", target: "to flood" },
  { source: "inquiet/inquiète", target: "worried" },
  { source: "instituteur", target: "primary school teacher" },
  { source: "institutrice", target: "primary school teacher" },
  { source: "instruction civique", target: "citizenship" },
  { source: "interdit", target: "forbidden, not allowed" },
  { source: "intéressant", target: "interesting" },
  { source: "internaute", target: "internet user" },
  { source: "interprète", target: "interpreter" },
  { source: "inutile", target: "useless" },
  { source: "ivre", target: "drunk" },
  { source: "jaloux/jalouse", target: "jealous" },
  { source: "jambon", target: "ham" },
  { source: "jardin zoologique", target: "zoo" },
  { source: "jardinage", target: "gardening" },
  { source: "jeter", target: "to throw" },
  { source: "jeu", target: "game" },
  { source: "jeu télévisé", target: "game show" },
  { source: "jeune", target: "young" },
  { source: "jeunesse", target: "youth" },
  { source: "Jobs, career choices & ambitions", target: "" },
  { source: "Jobs, career choices and ambitions", target: "" },
  { source: "joli", target: "pretty" },
  { source: "Jour deAn", target: "New Year’s Day" },
  { source: "jour férié", target: "public holiday" },
  { source: "jour", target: "day" },
  { source: "journal", target: "newspaper" },
  { source: "journée", target: "day" },
  { source: "joyeux Noël", target: "Merry Christmas" },
  { source: "juif/juive", target: "Jewish" },
  { source: "jumeau/jumelle", target: "twin" },
  { source: "jumelé", target: "twinned" },
  { source: "jupe", target: "skirt" },
  { source: "jusqu’à", target: "up to" },
  { source: "juste", target: "correct" },
  { source: "là", target: "there" },
  { source: "la carte", target: "menu" },
  { source: "la perte", target: "loss" },
  { source: "là-bas", target: "over there" },
  { source: "lac", target: "lake" },
  { source: "laid", target: "ugly" },
  { source: "laine", target: "wool" },
  { source: "laisser", target: "toave" },
  { source: "laisser tomber", target: "to drop" },
  { source: "lait", target: "milk" },
  { source: "langue", target: "language" },
  { source: "langues vivantess", target: "modernnguages" },
  { source: "large", target: "wide" },
  { source: "lavabo", target: "wash basin" },
  { source: "laver", target: "to wash" },
  { source: "laver", target: "to wash" },
  {
    source: "lèche-vitrine",
    target: "window shopping",
  },
  { source: "leçon", target: "lesson" },
  { source: "lecteur DVD", target: "DVD player" },
  { source: "lecteur MP3", target: "MP3 player" },
  { source: "lecture", target: "reading" },
  { source: "légumess", target: "vegetables" },
  { source: "lendemain", target: "the next day" },
  { source: "lentement", target: "slowly" },
  { source: "les noces", target: "wedding" },
  { source: "lever", target: "to lift" },
  { source: "liberté", target: "freedom" },
  { source: "librairie", target: "bookshop" },
  { source: "libre", target: "free, vacant" },
  { source: "licence", target: "degree" },
  { source: "lieu", target: "place" },
  { source: "Life at school/college", target: "" },
  { source: "Life at school/college", target: "" },
  { source: "lire", target: "to read" },
  { source: "lit", target: "bed" },
  { source: "lits superposéss", target: "bunk beds" },
  { source: "livre", target: "pound" },
  { source: "livrer", target: "to deliver" },
  { source: "location de voitures", target: "car rental" },
  { source: "logement", target: "accommodation" },
  { source: "loger", target: "to stay" },
  { source: "logiciel", target: "software" },
  { source: "loin de", target: "far from" },
  { source: "loisir", target: "free time" },
  { source: "Londres", target: "London" },
  { source: "long/longue", target: "long" },
  { source: "longtemps", target: "for a long time" },
  { source: "louer", target: "to hire" },
  { source: "lourd", target: "heavy" },
  { source: "loyer", target: "rent" },
  { source: "lumière", target: "light" },
  { source: "lunettes de soleils", target: "sun glasses" },
  { source: "lunettess", target: "glasses" },
  { source: "lutter", target: "to struggle" },
  { source: "lycée", target: "sixth form college, grammar school" },
  { source: "maçon", target: "builder" },
  { source: "maigre", target: "skinny" },
  { source: "maillot de bain", target: "swimming costume" },
  { source: "maintenant", target: "now" },
  { source: "mairie", target: "town hall" },
  { source: "mais", target: "but" },
  {
    source: "maison",
    target: "house",
  },
  { source: "mal équipé", target: "badly equipped" },
  { source: "mal/plus mal/le plus mal", target: "badly/worse/worst" },
  { source: "malade", target: "ill" },
  { source: "maladie", target: "illness" },
  { source: "malgré", target: "despite, in spite of" },
  { source: "malsain", target: "unhealthy" },
  { source: "Manche", target: "English Channel" },
  { source: "manifestation", target: "demonstration" },
  { source: "mannequin", target: "model" },
  { source: "manquer", target: "to miss" },
  { source: "manteau", target: "overcoat" },
  { source: "maquillage", target: "make up" },
  { source: "marché", target: "market" },
  { source: "marcher", target: "to walk" },
  { source: "marée", target: "tide" },
  { source: "mari", target: "husband" },
  { source: "Maroc/marocain", target: "Morocco/Moroccan" },
  { source: "marque", target: "make,bel" },
  { source: "marquer un but/un essai", target: "to score a goal/try" },
  { source: "marrant", target: "funny" },
  { source: "marre", target: "(to be) fed up" },
  { source: "marre", target: "(to be) fed up" },
  { source: "marron", target: "brown" },
  { source: "maternelle", target: "nursery school" },
  { source: "matière", target: "subject" },
  { source: "matières grassess", target: "fats" },
  { source: "matin", target: "morning" },
  { source: "mauvais", target: "bad" },
  { source: "mauvais/pire/le pire", target: "bad/worse/worst" },
  { source: "Me, my family and friends", target: "" },
  { source: "Me, my family and friends", target: "" },
  { source: "mécanicien", target: "mechanic" },
  { source: "méchant", target: "naughty" },
  { source: "médecin", target: "doctor" },
  { source: "médicament", target: "medicine" },
  { source: "Méditerranée", target: "Mediterranean" },
  { source: "meilleurs voeux", target: "best wishes" },
  { source: "même si", target: "even if" },
  { source: "mener", target: "toad" },
  { source: "mentir", target: "to lie" },
  { source: "mépriser", target: "to despise" },
  { source: "merveilleux/merveilleuse", target: "marvellous" },
  { source: "messe", target: "mass" },
  { source: "météo", target: "weather forecast" },
  { source: "mettre", target: "to put" },
  { source: "mettre deargent de côté", target: "to save money" },
  { source: "mettre en ligne", target: "to upload" },
  { source: "meubless", target: "furniture" },
  { source: "mi-long", target: "mediumngth" },
  { source: "mignon/mignonne", target: "cute" },
  { source: "mince", target: "slim" },
  { source: "moche", target: "ugly" },
  { source: "mode", target: "fashion" },
  { source: "mois", target: "month" },
  { source: "moitié", target: "half" },
  { source: "monde", target: "world" },
  { source: "mondial", target: "worldwide" },
  { source: "moniteur", target: "monitor" },
  { source: "montagne", target: "mountain" },
  { source: "monter", target: "to go up/ascend" },
  { source: "moquette", target: "carpet" },
  { source: "morceau", target: "piece" },
  { source: "mort", target: "dead" },
  { source: "mosquée", target: "Mosque" },
  { source: "mot de passe", target: "password" },
  { source: "moto", target: "motor bike" },
  { source: "mouillé", target: "wet" },
  { source: "mourir", target: "to die" },
  { source: "moyen/moyenne", target: "medium" },
  { source: "mur", target: "wall" },
  { source: "musculation", target: "weight training" },
  { source: "musée", target: "museum" },
  { source: "musulman", target: "Muslim" },
  { source: "My studies", target: "" },
  { source: "My studies", target: "" },
  { source: "nager", target: "to swim" },
  { source: "naissance", target: "birth" },
  { source: "naître", target: "to be born" },
  { source: "natation", target: "swimming" },
  { source: "né(e)...", target: "born on the..." },
  { source: "ne jamais", target: "never" },
  { source: "ne pas", target: "not" },
  { source: "ne personne", target: "nobody, no-one" },
  { source: "ne plus", target: "no more, no longer" },
  { source: "ne que", target: "only, nothing but" },
  { source: "ne rien", target: "nothing" },
  { source: "neiger", target: "to snow" },
  { source: "nettoyer", target: "to clean" },
  { source: "neuvième", target: "ninth" },
  { source: "neveu", target: "nephew" },
  { source: "ni ni", target: "neither….nor" },
  { source: "niveau", target: "level" },
  { source: "noisette", target: "hazel" },
  { source: "noix", target: "nut" },
  { source: "nom", target: "name" },
  { source: "nombre de", target: "number of" },
  { source: "nombre", target: "number" },
  { source: "nord", target: "north" },
  { source: "normalement", target: "normally" },
  { source: "note", target: "mark" },
  { source: "nourriture bio", target: "organic food" },
  { source: "nourriture", target: "food" },
  { source: "nouveau", target: "new" },
  { source: "nuage", target: "cloud" },
  { source: "nuageux", target: "cloudy" },
  { source: "nuit", target: "night" },
  { source: "nul", target: "rubbish" },
  { source: "nulle part", target: "nowhere" },
  { source: "numérique", target: "digital" },
  { source: "obésité", target: "obesity" },
  { source: "obligatoire", target: "compulsory" },
  { source: "occupé", target: "taken, occupied" },
  { source: "odeur", target: "smell" },
  { source: "œuf", target: "egg" },
  { source: "oignon", target: "onion" },
  { source: "ombre", target: "shade" },
  { source: "ondulé", target: "wavy" },
  { source: "or", target: "gold" },
  { source: "orage", target: "storm" },
  { source: "orageux", target: "stormy" },
  { source: "ordinateur", target: "computer" },
  { source: "ordinateur portable", target: "laptop" },
  { source: "ordinateur tablette", target: "tablet" },
  { source: "orduress", target: "rubbish" },
  { source: "ou", target: "or" },
  { source: "où ?", target: "where?" },
  { source: "oublier", target: "to forget" },
  { source: "ouest", target: "west" },
  { source: "outil", target: "tool" },
  { source: "ouvert", target: "open" },
  { source: "ouvrir", target: "to open" },
  { source: "page d’accueil", target: "welcome page" },
  { source: "paix", target: "peace" },
  { source: "pamplemousse", target: "grapefruit" },
  { source: "pantalon", target: "trousers" },
  { source: "Pâques", target: "Easter" },
  { source: "paquet", target: "packet" },
  { source: "par", target: "by" },
  { source: "par contre", target: "on the other hand" },
  { source: "par exemple", target: "for example" },
  { source: "paraître", target: "to seem" },
  { source: "parc d’attractions", target: "theme park" },
  { source: "parc", target: "park" },
  { source: "pardon", target: "excuse me" },
  { source: "paresseux/paresseuse", target: "lazy" },
  { source: "parfait", target: "perfect" },
  { source: "parfait", target: "perfect" },
  { source: "parfois", target: "sometimes" },
  { source: "parfum", target: "perfume" },
  { source: "parmi", target: "amongst" },
  { source: "partager", target: "to share" },
  { source: "partenaire/la", target: "partner" },
  { source: "partir", target: "toave" },
  { source: "partout", target: "everywhere" },
  { source: "pas encore", target: "not yet" },
  { source: "pas mal de", target: "lots of" },
  { source: "passé", target: "past" },
  { source: "passe-temps", target: "hobby" },
  { source: "passer du temps", target: "to spend time" },
  { source: "passer un examen", target: "to sit an exam" },
  { source: "passionnant", target: "exciting" },
  { source: "pâtess (f)", target: "pasta" },
  { source: "patinage à glace", target: "ice skating" },
  { source: "patinoire", target: "ice rink" },
  { source: "pâtisserie", target: "cake shop" },
  { source: "patron; patronne", target: "boss" },
  { source: "pause", target: "break" },
  { source: "pauvre", target: "poor" },
  { source: "pauvreté", target: "poverty" },
  { source: "payer", target: "to pay" },
  { source: "paysage", target: "countryside/landscape" },
  { source: "peau", target: "skin" },
  { source: "pêche", target: "fishing/peach" },
  { source: "peine", target: "the bother" },
  { source: "pelouse", target: "lawn" },
  { source: "pendant", target: "during" },
  { source: "pendant que", target: "while" },
  { source: "pénible", target: "annoying" },
  { source: "penser", target: "to think" },
  { source: "penser", target: "to think" },
  { source: "Pentecôte", target: "Whitsuntide" },
  { source: "perdre", target: "to lose" },
  { source: "permettre", target: "to allow" },
  { source: "permis de conduire", target: "driving licence" },
  { source: "personnes défavoriséess", target: "disadvantaged people" },
  { source: "peser", target: "to weigh" },
  { source: "petit ami", target: "boyfriend" },
  { source: "petit déjeuner", target: "breakfast" },
  { source: "petit job", target: "part-time job" },
  { source: "petit-fils", target: "grandson" },
  { source: "petite amie", target: "girlfriend" },
  { source: "petite-fille", target: "grand-daughter" },
  { source: "petits poiss", target: "peas" },
  { source: "pétrole", target: "oil" },
  { source: "peu/moins/le moins", target: "few, little/less/theast" },
  { source: "peut-être", target: "perhaps" },
  { source: "physique", target: "physics" },
  { source: "pièce d’identité", target: "means of identification" },
  { source: "pièce", target: "room" },
  { source: "pile", target: "battery" },
  { source: "piquant", target: "spicy" },
  { source: "piscine", target: "swimming pool" },
  { source: "piste cyclable", target: "cyclene" },
  { source: "place", target: "square" },
  { source: "plage", target: "beach" },
  { source: "plaire", target: "to please" },
  { source: "plan de ville", target: "town plan" },
  { source: "planche à voile", target: "wind-surfing" },
  { source: "plat principal", target: "main meal/dish" },
  { source: "plein de", target: "full of, lots of" },
  { source: "pleuvoir", target: "to rain" },
  { source: "plombier", target: "plumber" },
  { source: "plongée sous-marine", target: "underwater diving" },
  { source: "pluie", target: "rain" },
  { source: "plus que/moins que", target: "more than/less than" },
  { source: "plus tard", target: "later" },
  { source: "plus/moins", target: "more/less" },
  { source: "pointure", target: "size" },
  { source: "poire", target: "pear" },
  { source: "poisson d’avril", target: "April Fools' Day, April Fool!" },
  { source: "poisson", target: "fish" },
  { source: "poivre", target: "pepper" },
  { source: "policier", target: "policeman" },
  { source: "pollué", target: "polluted" },
  { source: "pomme de terre", target: "potato" },
  { source: "pomme", target: "apple" },
  { source: "portable", target: "mobile" },
  { source: "porte-monnaie", target: "purse" },
  { source: "portefeuille", target: "wallet" },
  { source: "porter", target: "to wear" },
  { source: "poser", target: "to put down" },
  { source: "poste", target: "post office" },
  { source: "potage", target: "soup" },
  { source: "poubelle", target: "dustbin" },
  { source: "poulet", target: "chicken" },
  { source: "pour", target: "for, in order to" },
  { source: "pour combien de temps ?", target: "for how long?" },
  { source: "pourboire", target: "tip" },
  { source: "pourpre", target: "purple" },
  { source: "pourquoi ?", target: "why?" },
  { source: "pourtant", target: "however" },
  { source: "pouvoir", target: "to be able" },
  { source: "pratique", target: "practical" },
  { source: "préférer", target: "to prefer" },
  { source: "premier", target: "first" },
  { source: "prendre", target: "to take" },
  { source: "prénom", target: "first name" },
  { source: "près de", target: "near" },
  { source: "presque", target: "almost" },
  { source: "pressé", target: "in a hurry, rushed/squeezed" },
  { source: "pression", target: "pressure" },
  { source: "prêt", target: "ready" },
  { source: "printemps", target: "spring" },
  { source: "prix", target: "price" },
  { source: "prochain", target: "next" },
  { source: "produire", target: "to provide" },
  { source: "produits bios", target: "green products" },
  { source: "professeur", target: "teacher" },
  { source: "projet", target: "plan" },
  { source: "promenade", target: "walk" },
  { source: "promettre", target: "to promise" },
  { source: "propre", target: "clean" },
  { source: "propriétaire/la", target: "owner" },
  { source: "protéger", target: "to protect" },
  { source: "proviseur", target: "head teacher" },
  { source: "prune", target: "plum" },
  { source: "publicité", target: "adverts" },
  { source: "puis", target: "then" },
  { source: "puisque", target: "seeing that" },
  { source: "pull à capuche", target: "hoodie" },
  { source: "pull", target: "jumper" },
  { source: "qu’est-ce que ?", target: "what?" },
  { source: "qu’est-ce que c’est ?", target: "what is it?" },
  { source: "qu’est-ce qui ?", target: "what?" },
  { source: "quand", target: "when" },
  { source: "quand?", target: "when?" },
  { source: "quartier", target: "quarter" },
  { source: "quatrième", target: "fourth" },
  { source: "que ?", target: "what?" },
  { source: "que veut dire… ?", target: "what does... mean?" },
  { source: "quel dommage", target: "what a pity" },
  { source: "quel/quelle?", target: "which?" },
  { source: "quelle heure est-il ?", target: "what time is it?" },
  { source: "quelque part", target: "somewhere" },
  { source: "quelquefois", target: "sometimes" },
  { source: "qui ?", target: "who?" },
  { source: "quitter", target: "toave" },
  { source: "quoi ?", target: "what?" },
  { source: "quotidien(ne)", target: "daily" },
  { source: "raide", target: "straight" },
  { source: "raisinss", target: "grapes" },
  { source: "ralentir", target: "to slow down" },
  { source: "ramasser", target: "to pick up" },
  { source: "randonnée", target: "walk" },
  { source: "ranger", target: "to tidy" },
  { source: "rapportss", target: "relationships" },
  { source: "rarement", target: "rarely" },
  { source: "rayon", target: "department" },
  { source: "récemment", target: "recently" },
  { source: "recevoir", target: "to receive" },
  { source: "recevoir", target: "to receive" },
  { source: "réchauffement de Terre", target: "global warming" },
  { source: "reconnaissant", target: "grateful" },
  { source: "récré(ation)", target: "break" },
  { source: "redoubler", target: "to repeat the year" },
  { source: "réduire", target: "to reduce" },
  { source: "réduit", target: "reduced" },
  { source: "réfugié", target: "refugee" },
  { source: "règle", target: "rule" },
  { source: "règlement", target: "school rules" },
  { source: "religieux/religieuse", target: "religious" },
  { source: "religion", target: "religious studies" },
  { source: "remarquer", target: "to notice" },
  { source: "rembourser", target: "to reimburse" },
  { source: "remercier", target: "to thank" },
  { source: "remplir", target: "to fill" },
  { source: "rencontrer", target: "to meet" },
  { source: "rendez-vous", target: "meeting" },
  { source: "renoncer", target: "to give up" },
  { source: "renseignementss", target: "information" },
  { source: "rentrée", target: "return to school" },
  { source: "repas", target: "meal" },
  { source: "repas", target: "meal" },
  { source: "répéter", target: "to repeat" },
  { source: "réponse", target: "reply" },
  { source: "réseau social", target: "social network" },
  { source: "réserver", target: "to book" },
  { source: "respirer", target: "to breathe" },
  { source: "rester", target: "to stay" },
  { source: "rester", target: "to stay" },
  { source: "rester en contact", target: "to stay in contact" },
  { source: "résultat", target: "result" },
  { source: "retenue", target: "detention" },
  { source: "retour", target: "return" },
  { source: "retourner", target: "to return" },
  { source: "réunion", target: "meeting" },
  { source: "réussir", target: "to succeed" },
  { source: "réussir un examen", target: "to pass an exam" },
  { source: "rêve", target: "dream" },
  { source: "revenir", target: "to come back" },
  { source: "rêver", target: "to dream" },
  { source: "rez-de-chaussée", target: "ground floor" },
  { source: "ridicule", target: "ridiculous" },
  { source: "rigolo", target: "funny" },
  { source: "risque", target: "risk" },
  { source: "rivière", target: "river" },
  { source: "riz", target: "rice" },
  { source: "robe", target: "dress" },
  { source: "robinet", target: "tap" },
  { source: "rond", target: "round" },
  { source: "rose", target: "pink" },
  { source: "route", target: "road" },
  { source: "roux", target: "ginger" },
  { source: "s’abonner", target: "to subscribe" },
  { source: "s’appeler", target: "to be called" },
  { source: "s’asseoir", target: "to sit down" },
  { source: "s’enivrer", target: "to get drunk" },
  { source: "s’entendre (avec)", target: "to get on (with)" },
  { source: "s’entraîner", target: "to train" },
  { source: "s’il te/vous plaît", target: "please" },
  { source: "s’inquiéter", target: "to worry" },
  { source: "s’intéresser à", target: "to be interested in" },
  { source: "sable", target: "sand" },
  { source: "sac de couchage", target: "sleeping bag" },
  { source: "sac en plastique", target: "plastic bag" },
  { source: "sage", target: "well behaved" },
  { source: "sain", target: "healthy" },
  { source: "Saint Valentin", target: "St. Valentine’s Day" },
  { source: "Saint-Sylvestre", target: "New Year’s Eve" },
  { source: "sale", target: "dirty" },
  { source: "salé", target: "salty" },
  { source: "salle à manger", target: "dining room" },
  { source: "salle de bains", target: "bathroom" },
  { source: "salle de classe", target: "classroom" },
  { source: "salle de séjour", target: "lounge" },
  { source: "salon", target: "living room" },
  { source: "salut", target: "hi" },
  {
    source: "SAMU service d’aide médicale d’urgence",
    target: "emergency medical services",
  },
  { source: "sans", target: "without" },
  { source: "sans doute", target: "undoubtedly, without doubt" },
  { source: "sans-abri", target: "homeless person" },
  { source: "santé", target: "cheers" },
  { source: "santé", target: "health" },
  { source: "saucisse", target: "sausage" },
  { source: "saumon", target: "salmon" },
  { source: "sauvegarder", target: "to save" },
  { source: "sauver", target: "to save" },
  { source: "savoir", target: "to know" },
  { source: "scolaire", target: "school" },
  { source: "SDF sans domicile fixe", target: "homeless person" },
  { source: "se coucher", target: "to go to bed" },
  { source: "se débrouiller", target: "to get by, to cope" },
  { source: "se disputer", target: "to argue" },
  { source: "se faire des amis", target: "to make friends" },
  { source: "se marier", target: "to get married" },
  { source: "se mettre en colère", target: "to get angry" },
  { source: "se mettre en route", target: "to set off" },
  { source: "se présenter", target: "to introduce oneself" },
  { source: "se promener", target: "to go for a walk" },
  { source: "se tromper", target: "to make a mistake" },
  { source: "se trouver", target: "to be situated" },
  { source: "se détendre", target: "to relax" },
  { source: "se droguer", target: "to take drugs" },
  { source: "se relaxer", target: "to relax" },
  { source: "se rendre compte", target: "to realise" },
  { source: "séance", target: "performance" },
  { source: "Seasons", target: "" },
  { source: "sec/sèche", target: "dry" },
  { source: "sécurité", target: "safety" },
  { source: "séjour", target: "stay" },
  { source: "sel", target: "salt" },
  { source: "selon", target: "according to" },
  { source: "semaine", target: "week" },
  { source: "sembler", target: "to seem" },
  { source: "sens dehumour", target: "sense of humour" },
  { source: "sensass", target: "sensational" },
  { source: "séparé", target: "separated" },
  { source: "septième", target: "seventh" },
  { source: "série", target: "series" },
  { source: "serveur/serveuse", target: "waiter" },
  { source: "seulement", target: "only" },
  { source: "si", target: "if" },
  { source: "sida", target: "AIDS" },
  { source: "siècle", target: "century" },
  { source: "site internet/web", target: "website" },
  { source: "situé", target: "situated" },
  { source: "sixième", target: "sixth" },
  { source: "skate", target: "skateboarding" },
  { source: "ski", target: "(water) skiing" },
  {
    source: "SNCF société nationale des chemins de fer français",
    target: "National Rail Service",
  },
  { source: "Social issues", target: "" },
  { source: "Social issues", target: "" },
  { source: "soie", target: "silk" },
  { source: "soigner", target: "to care for" },
  { source: "soin", target: "care" },
  { source: "soir", target: "evening" },
  { source: "soldess", target: "sale" },
  { source: "sommeil", target: "sleep" },
  { source: "sommet", target: "summit" },
  { source: "sortie", target: "exit" },
  { source: "sortir", target: "to go out" },
  { source: "souci", target: "worry" },
  { source: "soudain", target: "suddenly" },
  { source: "souris", target: "mouse" },
  { source: "sous", target: "under" },
  { source: "sous-sol", target: "basement" },
  { source: "souvent", target: "often" },
  { source: "spectacle", target: "show" },
  { source: "sportif/sportive", target: "sporty" },
  { source: "sports d’hivers", target: "winter sports" },
  { source: "stade", target: "stadium" },
  { source: "station balnéaire", target: "seaside resort" },
  { source: "station-service", target: "service station" },
  { source: "steak haché", target: "burger" },
  {
    source:
      "Students are expected to know the cardinal numbers 0–1,000 and the word for 1,000,000.",
    target: "",
  },
  {
    source:
      "Students are expected to know thetters of the alphabet and appropriate accents.",
    target: "",
  },
  { source: "sucré", target: "sugary" },
  { source: "sucre", target: "sugar" },
  { source: "sud", target: "south" },
  { source: "suffisamment", target: "sufficiently" },
  { source: "Suisse/suisse", target: "Switzerland/Swiss" },
  { source: "suivant", target: "following" },
  { source: "suivre", target: "to follow" },
  { source: "supporter", target: "to put up with" },
  { source: "supporter", target: "to tolerate, put up with" },
  { source: "supprimer", target: "to suppress/eliminate" },
  { source: "sûr", target: "certain" },
  { source: "sur point de", target: "(to be) about to" },
  { source: "sur", target: "on" },
  { source: "surchargé", target: "overcrowded" },
  { source: "surfer sur Internet", target: "to surf the internet" },
  { source: "surveiller", target: "to watch" },
  { source: "sympa", target: "kind" },
  { source: "tabac", target: "newsagent’s" },
  { source: "tabac", target: "tobacco" },
  { source: "tabagisme", target: "addiction to smoking" },
  { source: "tableau", target: "board" },
  { source: "tâche", target: "task" },
  { source: "taille", target: "size" },
  { source: "tante", target: "aunt" },
  { source: "taper", target: "to type" },
  { source: "tard", target: "late" },
  { source: "tasse", target: "cup" },
  { source: "tatouage", target: "tattooing" },
  { source: "tchater", target: "to talk online" },
  { source: "Technology in everyday life", target: "" },
  { source: "Technology in everyday life", target: "" },
  { source: "télé réalité", target: "reality television" },
  { source: "télécharger", target: "to download" },
  { source: "témoin", target: "witness" },
  { source: "tempête", target: "storm" },
  { source: "temps", target: "weather" },
  { source: "temps libre", target: "free time" },
  { source: "tenter", target: "to attempt" },
  { source: "terrain de sport", target: "sports ground" },
  { source: "texto", target: "text" },
  { source: "TGV train à grande vitesse", target: "high-speed train" },
  { source: "thé", target: "tea" },
  {
    source: "They are also expected to know the ordinal numbers first-tenth.",
    target: "",
  },
  { source: "thon", target: "tuna" },
  { source: "Time expressions", target: "" },
  { source: "timide", target: "shy" },
  { source: "tonnerre", target: "thunder" },
  { source: "tôt", target: "early" },
  { source: "touche", target: "key" },
  { source: "toujours", target: "always" },
  { source: "tour", target: "tower" },
  { source: "tourisme", target: "tourism" },
  { source: "tournée", target: "tour" },
  { source: "tourner", target: "to turn" },
  { source: "tournoi", target: "tournament" },
  { source: "touss jours", target: "every day" },
  { source: "Toussaint", target: "All Saints' Day" },
  { source: "tousser", target: "to cough" },
  { source: "tout à coup", target: "suddenly, all of a sudden" },
  { source: "tout de suite", target: "immediately" },
  { source: "tout droit", target: "straight ahead" },
  { source: "tout près", target: "very near" },
  { source: "toutes directions", target: "all directions" },
  { source: "toxicomane/la", target: "drug addict" },
  { source: "traduire", target: "to translate" },
  { source: "traitement de texte", target: "word processing" },
  { source: "trajet", target: "journey" },
  { source: "tranche", target: "slice" },
  { source: "tranquille", target: "quiet" },
  { source: "transport en commun", target: "public transport" },
  { source: "travail bénévole", target: "voluntary work" },
  { source: "travailler", target: "to work" },
  { source: "travailleur/travailleuse", target: "hard-working" },
  { source: "Travel and tourism", target: "" },
  { source: "Travel and tourism", target: "" },
  { source: "traversée", target: "crossing" },
  { source: "tremper", target: "to soak" },
  { source: "trimestre", target: "term" },
  { source: "triste", target: "sad" },
  { source: "troisième", target: "third" },
  { source: "trop", target: "too" },
  { source: "trou", target: "hole" },
  { source: "trouver", target: "to find" },
  { source: "truite", target: "trout" },
  { source: "tuer", target: "to kill" },
  { source: "Tunisie/tunisien", target: "Tunisia/Tunisian" },
  {
    source: "TVA taxe sur valeur ajoutée",
    target: "VAT",
  },
  { source: "unique", target: "only" },
  { source: "usine", target: "factory" },
  { source: "utile", target: "useful" },
  { source: "utiliser", target: "to use" },
  { source: "vacancess", target: "holidays" },
  { source: "vague", target: "wave" },
  { source: "valise", target: "suitcase" },
  { source: "valoir mieux", target: "to be better" },
  { source: "varié", target: "varied" },
  { source: "veau", target: "veal" },
  { source: "vedette", target: "film star" },
  { source: "veille de Noël", target: "Christmas Eve" },
  { source: "vendeur/vendeuse", target: "shop assistant" },
  { source: "vendre", target: "to sell" },
  { source: "venir de", target: "to have just" },
  { source: "vent", target: "wind" },
  { source: "verre", target: "glass" },
  { source: "vers", target: "towards" },
  { source: "veste", target: "jacket" },
  { source: "vêtementss", target: "clothes" },
  { source: "vétérinaire", target: "vet" },
  { source: "viande", target: "meat" },
  { source: "vide", target: "empty" },
  { source: "vie", target: "life" },
  { source: "vieux/vieil/vieille", target: "old" },
  { source: "vif/vive", target: "lively" },
  { source: "ville", target: "town" },
  { source: "ville", target: "town" },
  { source: "visite", target: "(guided) visit" },
  { source: "vite", target: "quickly" },
  { source: "vitrine", target: "shop window" },
  { source: "vivre", target: "to live" },
  { source: "voile", target: "sailing" },
  { source: "voir", target: "to see" },
  { source: "voisin", target: "neighbour" },
  { source: "voiture", target: "car" },
  { source: "voix", target: "voice" },
  { source: "vol", target: "flight" },
  { source: "voler", target: "to fly" },
  { source: "voler", target: "to steal" },
  { source: "volley", target: "volleyball" },
  { source: "vomir", target: "to be sick" },
  { source: "vouloir", target: "to wish" },
  { source: "vouloir", target: "to wish" },
  { source: "voyager", target: "to travel" },
  { source: "voyou", target: "yob" },
  { source: "vrai", target: "TRUE" },
  { source: "vraiment", target: "really" },
  { source: "VTT vélo tout terrain", target: "mountain bike" },
  { source: "vue de mer", target: "sea view" },
  { source: "y compris", target: "including" },
  { source: "yaourt", target: "yoghurt" },
  { source: "yeuxs", target: "eyes" },
  { source: "zone piétonne", target: "pedestrian zone" },
];
